# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HackTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  pod 'Socket.IO-Client-Swift', '~> 15.2.0'
  # Pods for HackTest

end
